### PR TITLE
Add sites

### PR DESCRIPTION
**Pull request by qqux**
Nice project you've got there. Added some popular photography sites.

I see that there is a bunch of duplicate sites in the file - e.g. eBay. Is it okay to remove them? In case an entry is deleted, do you change all the ID numbers or do you keep them with gaps in the numeration?

### CODE REVIEW

**Comment by p1ngul1n0** [comment]
Hi @qqux,

Thanks for your contribution! Your name will be mentioned in the contributors section in README.

About the remove of a incorrect or duplicate site, i need to manually fix the IDs when this happens. In a near future i plan to change these IDs to something more unique, like UUIDs.

But if you found i duplicate site, make a PR removing it, i accept it and after that i fix the IDs manually.

**Review by p1ngul1n0 — CHANGES_REQUESTED** [review]
The new sites, from ID 576 to 581 have a ":" after the "app" property, it needs to have a ",".

Please fix that so i can approve your PR

**Comment by qqux** [comment]
Yep. I pasted the config from an editor to a remote server in order to test the changes, fixed the syntax error on a remote server and must have forgotten to paste it back. There were no changes to the logic though.

**Comment by p1ngul1n0** [comment]
Great! Just accepted your PR. Thanks for your help with the project.

**Pull request merged**
