### PR TITLE
Custom ports

### PR DESCRIPTION
**Pull request by tjhasan**
Added a new argument `--port` that allows the user to specify which port to deploy blackbird on. 

This should be useful for users who may have port 5000 occupied. 

Port 5000 is set by default. 

This should close issue #13

### CODE REVIEW

**Comment by p1ngul1n0** [comment]
Hi Tjhasan!

The problem with using custom ports is that the FrontEnd won't be able to comunicate with the webserver because the URL is fixed in JavaScript.

I could change the default port to another that almost no service use, what do you think?

image

**Comment by tjhasan** [comment]
Interesting, I didn't take that into consideration. Is there no way to tell React the custom port to fetch from?

**Comment by p1ngul1n0** [comment]
As far as I know this can't be done, cause React needs to be build.

**Comment by tjhasan** [comment]
That's really unfortunate. Yeah in that case let's go with your idea of changing the default port to something else. I'll keep trying to see if there's someway around this in the meantime.

**Comment by p1ngul1n0** [comment]
Hi Tjhasan, just modified the port to 9797.

**Pull request closed without merging**
