### PR TITLE
Reformat code with classes

### PR DESCRIPTION
**Pull request by Pandede**
Continue the progress in #26 
1. `webserver.py` is coming back
2. Merge the new commits from @p1ngul1n0 \
    - new function `get_image` of `Webserver`
    - updated list of websites

### CODE REVIEW

**Comment by Pandede** [comment]
Is this any consideration? I may write some unit tests if needed.

**Comment by p1ngul1n0** [comment]
Hi Pandede, i just sent you a mail so we can talk.

**Comment by p1ngul1n0** [comment]
Sorry @Pandede i had to revert the commit, tested the code and didn't worked, please test and pull a new request.

**Comment by Pandede** [comment]
Sure, I may fix it later.

**Pull request merged**
